{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "codefreak.serviceAccountName" . }}-rb
  # We create a role-bindung for our service account in another namespace
  namespace: {{ default .Release.Namespace .Values.workspaces.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "codefreak.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "codefreak.serviceAccountRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
